### ISSUE TITLE
an issue while testing tsx components

### ISSUE THREAD

**Issue by zdravkov** [vuejs/vue-test-utils-typescript-example#2]
Hi 

I am trying to create sample boilerplate with a similar configuration but have an issue with testing the tsx component. Do you have a recommendation for such scenarios.

Project here - https://github.com/zdravkov/vue-tsx-files-boilerplate

Greetings,
Plamen

**Comment by eddyerburgh** [comment]
Hi, this issue tracker is reserved for bugs. Please ask questions on StackOverflow, or on the official forum.

**Comment by zdravkov** [comment]
If anybody needs such solution I have solved it by using this module - [typescript-babel-jest](https://www.npmjs.com/package/typescript-babel-jest). The linked repository is updated with runnable tests.
