### ISSUE TITLE
Cannot find name 'describe'.

### ISSUE THREAD

**Issue by dadabread888** [vuejs/vue-test-utils-typescript-example#4]
Hi, 
I clone the sample and installed, it's alarming "Cannot find name 'describe'."
Did I miss anything?

**Comment by eddyerburgh** [comment]
Did you install with npm?

**Comment by Carsten64** [comment]
just go to the test file and import 'import 'jest';'

**Comment by eddyerburgh** [comment]
Thanks @Carsten64. Closed with 6df01bd762414001162a62ced746b2180e3b0070
